name: virsorter2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - amply=0.1.6=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - arrow=1.3.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - coin-or-cbc=2.10.12=h00e76a6_2
  - coin-or-cgl=0.60.9=h82e2f02_4
  - coin-or-clp=1.17.10=h8a7a1e7_1
  - coin-or-osi=0.108.11=h96cc833_4
  - coin-or-utils=2.11.12=h3a12e53_2
  - coincbc=2.10.12=2_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=23.7.4=py310hff52083_0
  - conda-package-handling=1.9.0=py310h5764c6d_1
  - configargparse=1.7=pyhd8ed1ab_1
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cryptography=44.0.2=py310h6c63255_0
  - datrie=0.8.2=py310ha75aee5_8
  - docutils=0.21.2=pyhd8ed1ab_1
  - fmt=10.2.1=h00ab1b0_0
  - git=2.49.0=pl5321h59d505e_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libarchive=3.7.7=h4585015_3
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.13.0=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libmamba=1.5.1=had39da4_2
  - libmambapy=1.5.1=py310h39ff949_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libsolv=0.7.31=h7955e40_1
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h81593ed_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=1.5.1=py310h51d5547_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310h89163eb_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.0.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - psutil=7.0.0=py310ha75aee5_0
  - pulp=2.7.0=py310hff52083_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310ha75aee5_2
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyopenssl=25.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.0=h543edf9_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python_abi=3.10=6_cp310
  - pyyaml=6.0.2=py310h89163eb_2
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.24.0=py310hc1293b2_0
  - ruamel.yaml=0.16.12=py310h5764c6d_3
  - ruamel.yaml.clib=0.2.8=py310ha75aee5_1
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake-minimal=5.26.0=py_0
  - sqlite=3.49.1=h9eae976_2
  - text-unidecode=1.3=pyhd8ed1ab_2
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=1.0.0=pyhd8ed1ab_1
  - toposort=1.10=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - virsorter=2.2.4=pyhdfd78af_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py310ha75aee5_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py310ha75aee5_1
  - zstd=1.5.7=hb8e6e7a_2
