name: env_7
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20200923.3=h2531618_0
  - absl-py=2.1.0=py38h06a4308_0
  - aiohappyeyeballs=2.4.0=py38h06a4308_0
  - aiohttp=3.10.5=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astor=0.8.1=py38h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.3=py38h06a4308_0
  - attrs=24.2.0=py38h06a4308_0
  - blas=1.0=openblas
  - blinker=1.6.2=py38h06a4308_0
  - boost-cpp=1.70.0=h7b93d67_3
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachetools=5.3.3=py38h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - coverage=7.6.1=py38h5eee18b_0
  - cryptography=41.0.3=py38h130f0dd_0
  - cython=3.0.11=py38h5eee18b_0
  - diamond=2.0.4=h56fc30b_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - gast=0.3.3=py_0
  - giflib=5.2.2=h5eee18b_0
  - google-auth=2.29.0=py38h06a4308_0
  - google-auth-oauthlib=0.5.2=py38h06a4308_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.36.4=hf89561c_1
  - grpcio=1.36.1=py38h2157cd5_1
  - h5py=2.10.0=py38hd6299e0_1
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=67.1=he1b5a44_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=8.2.1=h91b91d3_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.52.0=ha637b67_1
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.15.8=h780b84a_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - lightgbm=3.2.1=py38h295c915_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py38h06a4308_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - multidict=6.0.4=py38h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.19.2=py38hc896f84_1
  - numpy-base=1.19.2=py38h21a3de8_1
  - oauthlib=3.2.2=py38h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py38h06a4308_0
  - pandas=1.4.0=py38h43a58ef_0
  - pip=24.2=py38h06a4308_0
  - prodigal=2.6.3=h7b50bb2_10
  - protobuf=3.15.8=py38h709712a_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.8.0=py38h06a4308_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.15=h7a1cb2a_2
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2024.1=py38h06a4308_0
  - re2=2021.04.01=h9c3ff4c_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_1
  - requests-oauthlib=2.0.0=py38h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=0.23.2=py38h0573a6f_0
  - scipy=1.8.0=py38h56a6a73_1
  - seqkit=2.8.2=h9ee0642_1
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.45.3=h5eee18b_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tensorflow=2.4.0=py38h578d9bd_0
  - tensorflow-base=2.4.0=py38h01d9eeb_0
  - tensorflow-estimator=2.4.0=pyh9656e83_0
  - termcolor=2.1.0=py38h06a4308_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py38h06a4308_0
  - tqdm=4.64.1=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=1.26.19=py38h06a4308_0
  - werkzeug=3.0.3=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - yarl=1.11.0=py38h5eee18b_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.4.9=haebb681_0
  - pip:
    - checkm2==1.0.2

