name: dastool
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - blast=2.16.0=h66d330f_5
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.13.0=h332b0f4_0
  - das_tool=1.1.3=r41hdfd78af_0
  - diamond=2.1.11=h5ca1c30_2
  - entrez-direct=22.4=he881be0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gawk=5.3.1=hcd3d067_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gdbm=1.18=h0a1914f_2
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - harfbuzz=11.1.0=h3beb420_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.23.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.23=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.84.1=h2ff4ddf_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsanitizer=14.2.0=hed042b8_2
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h4bc477f_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - mpfr=4.2.1=h90cbb55_3
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_0
  - pango=1.56.3=h9ac818e_1
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_1
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321h503566f_5
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scalar-list-utils=1.69=pl5321hb9d3cd8_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pixman=0.44.2=h29eaf8c_0
  - prodigal=2.6.3=h7b50bb2_10
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pullseq=1.0.2=h1104d80_11
  - r-base=4.1.3=h503823a_17
  - r-cli=3.6.1=r41h38f115c_0
  - r-codetools=0.2_19=r41hc72bb7e_0
  - r-colorspace=2.1_0=r41h133d619_0
  - r-crayon=1.5.2=r41hc72bb7e_1
  - r-data.table=1.14.8=r41h133d619_0
  - r-domc=1.3.8=r41ha770c72_1
  - r-ellipsis=0.3.2=r41h06615bd_1
  - r-fansi=1.0.4=r41h133d619_0
  - r-farver=2.1.1=r41h7525677_1
  - r-foreach=1.5.2=r41hc72bb7e_1
  - r-ggplot2=3.4.2=r41hc72bb7e_0
  - r-glue=1.6.2=r41h06615bd_1
  - r-gtable=0.3.3=r41hc72bb7e_0
  - r-isoband=0.2.7=r41h38f115c_1
  - r-iterators=1.0.14=r41hc72bb7e_1
  - r-labeling=0.4.2=r41hc72bb7e_2
  - r-lattice=0.21_8=r41h133d619_0
  - r-lifecycle=1.0.3=r41hc72bb7e_1
  - r-magrittr=2.0.3=r41h06615bd_1
  - r-mass=7.3_58.3=r41h133d619_0
  - r-matrix=1.5_4.1=r41h316c678_0
  - r-mgcv=1.8_42=r41he1ae0d6_0
  - r-munsell=0.5.0=r41hc72bb7e_1005
  - r-nlme=3.1_162=r41hac0b197_0
  - r-pillar=1.9.0=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_2
  - r-r6=2.5.1=r41hc72bb7e_1
  - r-rcolorbrewer=1.1_3=r41h785f33e_1
  - r-rlang=1.1.1=r41ha503ecb_0
  - r-scales=1.2.1=r41hc72bb7e_1
  - r-tibble=3.2.1=r41h133d619_1
  - r-utf8=1.2.3=r41h133d619_0
  - r-vctrs=0.6.2=r41ha503ecb_0
  - r-viridislite=0.4.1=r41hc72bb7e_1
  - r-withr=2.5.0=r41hc72bb7e_1
  - readline=8.2=h8c095d6_2
  - rpsbproc=0.5.0=hd6d6fdc_3
  - ruby=3.4.2=he7af4c9_0
  - sed=4.8=he412f7d_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tzdata=2025b=h78e105d_0
  - unzip=6.0=h7f98852_3
  - wget=1.21.4=hda4d442_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2

