name: vamb
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - archspec=0.2.5=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cpython=3.12.10=py312hd8ed1ab_0
  - dadaptation=3.2=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312h7201bc8_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libblas=3.9.0=31_hfdb39a5_mkl
  - libcblas=3.9.0=31_h372d94f_mkl
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_hc41d3b0_mkl
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libprotobuf=5.29.3=h501fc15_1
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtorch=2.6.0=cpu_mkl_hf6ddc5a_104
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h81593ed_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.3=h024ca30_0
  - loguru=0.7.2=py312h7900ff3_2
  - markupsafe=3.0.2=py312h178313f_1
  - mkl=2024.2.2=ha957f24_16
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.5=py312h72c5963_0
  - openssl=3.5.0=h7b32b05_0
  - optree=0.15.0=py312h68727a3_0
  - pip=25.0.1=pyh8b19718_0
  - psutil=7.0.0=py312h66e93f0_0
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pycoverm=0.6.2=py312h7f44c32_0
  - pyhmmer=0.11.0=py312h0fa9677_0
  - pyrodigal=3.6.3.post1=py312h0fa9677_0
  - python=3.12.10=h9e4cc4f_0_cpython
  - python_abi=3.12=7_cp312
  - pytorch=2.6.0=cpu_mkl_py312_h6a7998d_104
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.6.1=py312h7a48858_0
  - scipy=1.15.2=py312ha707e6e_0
  - setuptools=75.8.2=pyhff2d567_0
  - sleef=3.8=h1b44611_0
  - sympy=1.13.3=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - vamb=5.0.3=pyhdfd78af_0
  - vambcore=0.1.2=py312h6c9e832_1
  - wheel=0.45.1=pyhd8ed1ab_1

