name: semibin2_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - arpack=3.9.1=nompi_hf03ea27_102
  - bedtools=2.31.1=hf5e1c6e_2
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - coloredlogs=15.0.1=py312h06a4308_3
  - curl=8.12.1=h251f7ec_0
  - deprecated=1.2.13=py312h06a4308_0
  - filelock=3.17.0=py312h06a4308_0
  - fsspec=2024.12.0=py312h06a4308_0
  - gawk=5.3.1=h5eee18b_0
  - gettext=0.21.0=hedfda30_2
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - gsl=2.7=he838d99_0
  - hmmer=3.4=h503566f_3
  - htslib=1.21=h5efdd21_0
  - humanfriendly=10.0=py312h06a4308_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - k8=1.2=h6618dc6_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjemalloc=5.3.0=h5888daf_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libprotobuf=5.29.3=hc99497a_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtorch=2.5.1=cpu_openblas_h526855f_3
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libxml2=2.13.7=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=8.0.1=hc9558a2_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - metamdbg=0.3=hdcf5f25_0
  - minimap2=2.24=h7132678_1
  - mmseqs2=13.45111=pl5321hf1761c0_2
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py312h06a4308_0
  - nomkl=3.0=0
  - numexpr=2.10.1=py312hd28fd6d_0
  - numpy=2.2.4=py312h210a465_0
  - numpy-base=2.2.4=py312h80f3631_0
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openmp=8.0.1=0
  - openssl=3.5.0=h7b32b05_0
  - opentelemetry-api=1.30.0=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.32.1=0_h5eee18b_perl5
  - pip=25.0=py312h06a4308_0
  - prodigal=2.6.3=h7b50bb2_10
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-igraph=0.11.5=py312h4f72774_1
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=7_cp312
  - pytorch=2.5.1=cpu_openblas_py312hff96616_3
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - samtools=1.6=hc3601fc_10
  - scikit-learn=1.6.1=py312h6a678d5_0
  - scipy=1.15.2=py312h210a465_1
  - semibin=2.1.0=pyhdfd78af_0
  - setuptools=72.1.0=py312h06a4308_0
  - six=1.17.0=py312h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - sympy=1.13.3=py312h06a4308_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - texttable=1.6.4=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.67.1=py312he106c6f_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py312h06a4308_0
  - wfmash=0.8.2=h144baf3_0
  - wget=1.25.0=h251f7ec_0
  - wheel=0.45.1=py312h06a4308_0
  - wrapt=1.17.0=py312h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0

