name: mobileOG-db
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.79=py36h8f6f2f9_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - diamond=2.1.12=h13889ed_2
  - ld_impl_linux-64=2.43=h1423503_5
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libsqlite=3.50.1=hee588c1_4
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=1.19.5=py36hfc0c790_2
  - openssl=1.1.1w=hd590300_0
  - pandas=1.1.5=py36ha9443f7_0
  - pip=21.3.1=pyhd8ed1ab_0
  - prodigal=2.6.3=h7b50bb2_10
  - python=3.6.15=hb7a2778_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.2=h8c095d6_2
  - setuptools=58.0.4=py36h5fab9bb_2
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.1=h9eae976_4
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
