name: genomad
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.10=py311h2dc5d0c_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aragorn=1.2.41=h031d066_3
  - archspec=0.2.3=pyhd8ed1ab_0
  - aria2=1.37.0=h347180d_1
  - astunparse=1.6.3=pyhd8ed1ab_2
  - attrs=24.2.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cryptography=43.0.3=py311hafd3f86_0
  - flatbuffers=23.5.26=h59595ed_1
  - frozenlist=1.5.0=py311h9ecbd09_0
  - gast=0.5.5=pyhd8ed1ab_0
  - gawk=5.3.1=hcd3d067_0
  - genomad=1.8.1=pyhdfd78af_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - google-auth=2.36.0=pyhff2d567_0
  - google-auth-oauthlib=1.2.1=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - grpcio=1.59.3=py311ha6695c7_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py311hb639ac4_102
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keras=2.15.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.8.0=hca28451_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.09.01=h7a70373_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=2.1.2=cpu_h3a1dfae_0
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.43.0=py311h6a678d5_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h2dc5d0c_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - ml_dtypes=0.2.0=py311h320fe9a_2
  - mmseqs2=14.7e284=pl5321h6a68c12_2
  - mpfr=4.2.1=h90cbb55_3
  - multidict=6.1.0=py311h2dc5d0c_1
  - ncurses=6.5=he02047a_1
  - numba=0.60.0=py311h4bc866e_0
  - numpy=1.26.4=py311h64a7726_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=3.4.0=hb9d3cd8_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=24.3.1=pyh8b19718_0
  - propcache=0.2.0=py311h9ecbd09_2
  - protobuf=4.24.4=py311h46cbc50_0
  - py-xgboost=2.1.2=cpu_pyh15c3653_0
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyrodigal=3.6.3=py311hdad781d_0
  - pyrodigal-gv=0.3.2=pyh7e72e81_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.9=hb806964_0_cpython
  - python-crfsuite=0.9.9=py311h9547e67_2
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python_abi=3.11=5_cp311
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2023.09.01=h7f4b329_1
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rich-click=1.8.3=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py311h57cc02b_1
  - scipy=1.14.1=py311he9a78e4_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - taxopy=0.13.0=pyhdfd78af_0
  - tensorboard=2.15.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311hafd3f86_2
  - tensorflow=2.15.0=cpu_py311hd3d7757_2
  - tensorflow-base=2.15.0=cpu_py311h6aa969b_2
  - tensorflow-estimator=2.15.0=cpu_py311ha26c8b9_2
  - termcolor=2.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhff2d567_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - wrapt=1.14.1=py311hd4cff14_1
  - xgboost=2.1.2=cpu_pyhac85b48_0
  - xz=5.2.6=h166bdaf_0
  - yarl=1.16.0=py311h9ecbd09_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
