name: plasmer
channels:
  - iskoldt
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.43=h4bf12b8_2
  - biopython=1.84=py310hc51659f_0
  - blast=2.10.1=pl526he19e7b1_3
  - boost-cpp=1.74.0=h75c5d50_8
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - curl=7.88.1=hdc1c0ab_1
  - diamond=2.0.15=hb97b32f_1
  - entrez-direct=22.4=he881be0_0
  - expat=2.6.3=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gfortran_impl_linux-64=14.2.0=hc73f493_1
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2c03514_1
  - harfbuzz=6.0.0=h8e241bc_0
  - hmmer=3.3.2=hdbdd923_4
  - icu=70.1=h27087fc_0
  - infernal=1.1.4=h779adbc_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kmer-db=1.9.4=hd03093a_1
  - kraken2=2.1.2=pl5262h7d875b9_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=7.88.1=hdc1c0ab_1
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libpng=1.6.43=h2797004_0
  - libsanitizer=14.2.0=h2a3dede_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.2.0=h41c2201_101
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.5.1=h8b53f26_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=hcb278e6_0
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - numpy=2.1.3=py310hd6e36ab_0
  - openssl=3.3.2=hb9d3cd8_0
  - pango=1.50.14=hd33c08f_0
  - parallel=20240922=ha770c72_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.2=h59595ed_0
  - plasmer=23.04.20=py310_1
  - popt=1.16=h0b475e3_2002
  - prodigal=2.6.3=h031d066_9
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.10.14=hd12c33a_0_cpython
  - python_abi=3.10=5_cp310
  - r=4.2=r42hd8ed1ab_1007
  - r-base=4.2.3=h062c8ea_1
  - r-boot=1.3_30=r42hc72bb7e_0
  - r-class=7.3_22=r42h57805ef_1
  - r-cluster=2.1.6=r42h61816a4_0
  - r-codetools=0.2_20=r42hc72bb7e_0
  - r-foreign=0.8_87=r42hb1dbf0f_0
  - r-hash=3.0.1=r42hc72bb7e_4
  - r-kernsmooth=2.23_24=r42hc2011d3_0
  - r-lattice=0.22_6=r42h57805ef_0
  - r-mass=7.3_60.0.1=r42h57805ef_0
  - r-matrix=1.6_5=r42h316c678_0
  - r-mgcv=1.9_1=r42h316c678_0
  - r-nlme=3.1_165=r42hbcb9c34_0
  - r-nnet=7.3_19=r42h57805ef_1
  - r-randomforest=4.7_1.1=r42h61816a4_2
  - r-recommended=4.2=r42hd8ed1ab_1006
  - r-rpart=4.1.23=r42h57805ef_0
  - r-spatial=7.3_17=r42h57805ef_0
  - r-survival=3.7_0=r42hb1dbf0f_0
  - readline=8.2=h8228510_1
  - rsync=3.3.0=he6cb5fe_0
  - sed=4.8=he412f7d_0
  - seqkit=2.2.0=h9ee0642_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - tar=1.34=hb2e2bae_1
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tzdata=2024b=hc8b5060_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0

