name: plasmidhunter
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blast=2.16.0=hc155240_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.9.24=h06a4308_0
  - curl=8.8.0=he654da7_1
  - diamond=2.1.8=h43eeafb_0
  - entrez-direct=22.4=he881be0_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libcurl=8.8.0=hca28451_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgomp=14.2.0=h77fa898_1
  - libidn2=2.3.7=hd590300_0
  - libnghttp2=1.58.0=h47da74e_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - ncbi-vdb=3.1.1=h4ac6f70_2
  - ncurses=6.4=h6a678d5_0
  - openssl=3.3.2=hb9d3cd8_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_0
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321hdbdd923_2
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h4ac6f70_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_3
  - perl-parent=0.242=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-scalar-list-utils=1.63=pl5321hb9d3cd8_1
  - perl-storable=3.15=pl5321hb9d3cd8_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=24.2=py310h06a4308_0
  - prodigal=2.6.3=h031d066_9
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - rpsbproc=0.5.0=h6a68c12_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - biopython==1.84
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - idna==3.10
    - joblib==1.4.2
    - numpy==1.25.0
    - pandas==2.2.3
    - plasmidhunter==1.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - requests==2.32.3
    - scikit-learn==1.3.2
    - scipy==1.14.1
    - six==1.16.0
    - threadpoolctl==3.5.0
    - tzdata==2024.2
    - urllib3==2.2.3

