name: minimap2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - k8=1.2=he8db53b_5
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - libgcc=14.2.0=h77fa898_1
  - libgomp=14.2.0=h77fa898_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - minimap2=2.28=h577a1d6_4
  - python_abi=3.13=5_cp313
  - sysroot_linux-64=2.17=h0157908_18
  - tzdata=2025a=h78e105d_0

